RESK_WORDS_LIST = {
    "jailbreak", "bypass", "hack", "exploit", "override",
    "injection", "malware", "rootkit", "backdoor", "trojan",
    "phishing", "spyware", "keylogger", "ransomware", "botnet",
    "ddos", "xss", "sql injection", "buffer overflow", "zero-day",
    "brute force", "man-in-the-middle", "privilege escalation",
    "social engineering", "data breach", "identity theft",
    "cryptojacking", "malicious code", "exploit kit", "rat",
    "rootkit", "worm", "spear phishing", "vishing", "smishing",
    "doxing", "cyberstalking", "cyberextortion", "cyberterrorism",
    "advanced persistent threat", "apt", "watering hole attack",
    "evil twin", "rogue access point", "eavesdropping", "spoofing",
    "sniffing", "packet injection", "session hijacking", "backdoor",
    "logic bomb", "trojan horse", "virus", "polymorphic virus",
    "metamorphic virus", "macro virus", "boot sector virus",
    "file infector virus", "multipartite virus", "stealth virus",
    "armored virus", "cavity virus", "sparse infector virus",
    "companion virus", "fab virus", "overwrite virus", "parasitic virus",
    "resident virus", "non-resident virus", "tunneling virus",
    "multipartite virus", "cluster virus", "shell virus", "file virus",
    "macro virus", "polymorphic virus", "metamorphic virus",
    "encrypted virus", "stealth virus", "cavity virus", "sparse infector",
    "companion virus", "file overwriting virus", "file adding virus",
    "boot sector virus", "master boot record virus", "rootkit",
    "kernel rootkit", "user-mode rootkit", "firmware rootkit",
    "virtual rootkit", "bootkit", "hypervisor-level rootkit"
}